name: LinkWarden
description:
  LinkWarden is a powerful, self-hosted service designed for managing and
  archiving bookmarks. It provides an intuitive interface for organizing and
  accessing your saved links, supports advanced features for enhanced
  productivity, and offers detailed link preservation options. With LinkWarden,
  you can maintain control over your bookmarks and ensure they remain
  accessible.
instructions: Configure Environment Variables as per your needs.

changeLog:
  - date: 2025-01-16
    description: Template Release

links:
  - label: Documentation
    url: https://linkwarden.app/docs
  - label: Github
    url: https://github.com/linkwarden/linkwarden

contributors:
  - name: Ahson Shaikh
    url: https://github.com/Ahson-Shaikh

schema:
  type: object
  required:
    - appServiceName
    - appServiceImage
  properties:
    appServiceName:
      type: string
      title: App Service Name
      default: linkwarden
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/linkwarden/linkwarden:v2.9.3
benefits:
  - title: Advanced Bookmark Management
    description:
      LinkWarden allows you to organize, manage, and preserve your bookmarks
      efficiently through its intuitive web interface.
  - title: Self-Hosted Solution
    description:
      Stay in control of your bookmarks with a self-hosted service, ensuring
      privacy and customization.
  - title: Enhanced Productivity
    description:
      Access advanced features like tag management, link archiving, and
      note-taking to streamline your workflow.

features:
  - title: Bookmark Archiving
    description:
      Preserve web pages and links with offline access for long-term
      reliability.
  - title: Tag and Folder Organization
    description:
      Organize your bookmarks effectively with tags and folders for quick
      retrieval.
  - title: Shareable Collections
    description:
      Create and share bookmark collections with team members or friends.
  - title: Analytics Dashboard
    description:
      Gain insights into bookmark usage and access trends for better resource
      management.

tags:
  - Bookmark Manager
  - Self-Hosted
  - Productivity
  - Archiving
