name: SmokePing
description:
  SmokePing is a powerful open-source tool designed for network monitoring and
  latency measurement. It provides real-time visualizations of network latency
  and packet loss, making it easier to identify and diagnose connectivity
  issues. SmokePing uses ICMP and other protocols to monitor latency across
  multiple targets and generates detailed graphs to highlight network
  performance over time. It supports alerting, letting you know when latency or
  packet loss exceeds predefined thresholds. With its flexible configuration and
  plugin system, SmokePing can be adapted to various network environments,
  providing valuable insights into network health and reliability.
instructions:
  You may configure your targets by taking the console from Easypanel
changeLog:
  - date: 2025-01-21
    description: First Release
links:
  - label: Documentation
    url: https://oss.oetiker.ch/smokeping/doc/smokeping_install.en.html
  - label: Github
    url: https://github.com/oetiker/SmokePing
contributors:
  - name: Ahson Shaikh
    url: https://github.com/Ahson-Shaikh
schema:
  type: object
  required:
    - appServiceName
    - appServiceImage
  properties:
    appServiceName:
      type: string
      title: App Service Name
      default: smokeping
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/smokeping:2.8.2
benefits:
  - title: Real-Time Network Monitoring
    description:
      SmokePing provides real-time monitoring of network latency and packet
      loss, enabling quick detection of connectivity issues and bottlenecks.
  - title: Detailed Visualizations
    description:
      Generate detailed graphs that show latency trends and packet loss over
      time, providing actionable insights into network performance.
  - title: Customizable Alerts
    description:
      Configure alerts to notify you when latency or packet loss exceeds
      predefined thresholds, ensuring you are always informed about potential
      issues.
  - title: Flexible Configuration
    description:
      SmokePing supports a wide range of protocols and can be easily configured
      to monitor multiple network targets and scenarios.
  - title: Open Source and Extensible
    description:
      SmokePing is open-source and supports plugins, allowing you to extend its
      functionality to suit your specific network monitoring needs.
features:
  - title: Latency Measurement
    description:
      Measure network latency using ICMP and other supported protocols to
      provide accurate and reliable metrics.
  - title: Packet Loss Tracking
    description:
      Monitor and visualize packet loss across network targets to identify
      potential issues affecting connectivity.
  - title: Alerts and Notifications
    description:
      Set up custom alerts to notify you via email or other methods when network
      performance drops below acceptable levels.
  - title: Multi-Target Monitoring
    description:
      Monitor multiple network targets simultaneously, making it suitable for
      complex network environments.
  - title: Historical Data Retention
    description:
      Store and analyze historical data to identify trends and recurring issues
      in your network performance.
tags:
  - Network Monitoring
  - Latency Measurement
  - Open Source
  - Connectivity
  - Troubleshooting
