name: Picoshare
description:
  Picoshare is a lightweight, self-hosted file-sharing platform designed for
  simplicity and privacy. It provides a minimalistic interface for uploading,
  sharing, and managing files, without the complexity of traditional cloud
  storage services. Picoshare emphasizes ease of use and security, making it an
  ideal solution for personal or small team file-sharing needs. It supports a
  variety of file types and provides a secure, private environment for sharing
  files with full control over your data.
instructions: null
changeLog:
  - date: 2025-01-16
    description: First Release
links:
  - label: Website
    url: https://picoshare.net/
  - label: Documentation
    url: https://github.com/mtlynch/picoshare/wiki
  - label: Github
    url: https://github.com/mtlynch/picoshare
contributors:
  - name: Ahson Shaikh
    url: https://github.com/Ahson-Shaikh
schema:
  type: object
  required:
    - appServiceName
    - appServiceImage
    - authPassphrase
  properties:
    appServiceName:
      type: string
      title: App Service Name
      default: picoshare
    appServiceImage:
      type: string
      title: App Service Image
      default: mtlynch/picoshare:1.4.5
    authPassphrase:
      type: string
      title: Auth Passphrase
benefits:
  - title: Lightweight File Sharing
    description:
      Picoshare offers a lightweight and self-hosted solution for sharing files
      without the overhead of complex cloud storage services.
  - title: Privacy and Security
    description:
      With Picoshare, your files remain private and secure on your server,
      giving you full control over your data.
  - title: Simple User Interface
    description:
      Picoshare provides a clean, minimalistic interface that focuses on ease of
      use, making file sharing straightforward and hassle-free.
features:
  - title: Secure File Sharing
    description:
      Picoshare ensures secure file transfers, giving you peace of mind when
      sharing sensitive documents or media.
  - title: Support for Various File Types
    description:
      Share a wide range of file types, including documents, images, videos, and
      more, without compatibility concerns.
  - title: Self-Hosted Environment
    description:
      Host Picoshare on your own server, ensuring privacy and complete control
      over your file-sharing platform.
  - title: Minimal Resource Usage
    description:
      Picoshare is designed to be lightweight, making it efficient to run even
      on low-resource systems.
  - title: Easy Setup and Maintenance
    description:
      Picoshare is easy to set up and maintain, with clear documentation and
      minimal configuration required.
tags:
  - File Sharing
  - Privacy
  - Self-Hosted
