name: Raneto
description:
  Raneto is an open source Knowledgebase platform that uses static Markdown
  files to power your Knowledgebase.
instructions: null
changeLog:
  - date: 2022-11-27
    description: first release
links:
  - label: Website
    url: https://raneto.com
  - label: Documentation
    url: https://docs.linuxserver.io/images/docker-raneto
  - label: Github
    url: https://github.com/linuxserver/docker-raneto
contributors:
  - name: Serban Alexandru
    url: https://github.com/serban-alexandru
schema:
  type: object
  required:
    - appServiceName
    - appServiceImage
  properties:
    appServiceName:
      type: string
      title: App Service Name
      default: raneto
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/raneto:0.17.8
    serviceTimezone:
      type: string
      title: Timezone
      default: Etc/UTC
